{
 "title": "ConsumerWorkflowMetrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "StateBuild Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_StateBuild_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RetrieveObject (avg/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ConsumerWorkflowMetrics_RetrieveObjectFromState_Timer_count[1m])) by (le)"
    }
   ]
  },
  {
   "title": "RetrieveObjectFromState Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_RetrieveObjectFromState_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Decrypt Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_Decrypt_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ProcessStep (avg/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ConsumerWorkflowMetrics_ProcessStep_Timer_count[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ProcessStep Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_ProcessStep_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Decompress Perf",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_Decompress_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Acks (avg/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ConsumerWorkflowMetrics_AckMessage_Timer_count[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "AckMessage Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_AckMessage_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finalization (avg/s)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(ConsumerWorkflowMetrics_Finalization_Timer_count[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Finalization Perf",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(ConsumerWorkflowMetrics_Finalization_Timer_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}