name: nuget-publish

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Manual Publish'
  push:
    branches: [ 'nuget/publish' ]
  pull_request:
    branches: [ 'nuget/publish' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.301
    - name: Install dependencies
      run: dotnet restore Tesseract.sln
    - name: Build
      run: dotnet build Tesseract.sln --configuration Release --no-restore
    - name: Publish HouseofCat.Algorithms
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Algorithms/HouseofCat.Algorithms.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Compression
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Compression/HouseofCat.Compression.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Compression.LZ4
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Compression.LZ4/HouseofCat.Compression.LZ4.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper/HouseofCat.Dapper.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper.LegacySqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper.LegacySqlServer/HouseofCat.Dapper.LegacySqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dapper.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dapper.SqlServer/HouseofCat.Dapper.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dataflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dataflows/HouseofCat.Dataflows.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Dataflows.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Dataflows.Pipelines/HouseofCat.Dataflows.Pipelines.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Encryption
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Encryption/HouseofCat.Encryption.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Encryption.BouncyCastle
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Encryption.BouncyCastle/HouseofCat.Encryption.BouncyCastle.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Extensions
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Extensions/HouseofCat.Extensions.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Extensions.Dataflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Extensions.Dataflows/HouseofCat.Extensions.Dataflows.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Extensions.Host.SerilogSqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Extensions.Host.Serilog/HouseofCat.Extensions.Host.Serilog.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Framing
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Framing/HouseofCat.Framing.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Gremlins
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Gremlins/HouseofCat.Gremlins.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Gremlins.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Gremlins.SqlServer/HouseofCat.Gremlins.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Hashing
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Hashing/HouseofCat.Hashing.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Hashing.Argon
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Hashing.Argon/HouseofCat.Hashing.Argon.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Logger
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Logger/HouseofCat.Logger.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Metrics
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Metrics/HouseofCat.Metrics.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Metrics.Prometheus
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Metrics.Prometheus/HouseofCat.Metrics.Prometheus.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Network
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Network/HouseofCat.Network.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ/HouseofCat.RabbitMQ.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Client
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Client/HouseofCat.RabbitMQ.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Dataflows
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Dataflows/HouseofCat.RabbitMQ.Dataflows.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Pipelines
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Pipelines/HouseofCat.RabbitMQ.Pipelines.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Services
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Services/HouseofCat.RabbitMQ.Services.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Services.Mailkit
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Services.Mailkit/HouseofCat.RabbitMQ.Services.Mailkit.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.Services.Twilio
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.Services.Twilio/HouseofCat.RabbitMQ.Services.Twilio.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.RabbitMQ.WorkState
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.RabbitMQ.WorkState/HouseofCat.RabbitMQ.WorkState.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Reflection
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Reflection/HouseofCat.Reflection.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Serialization
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Serialization/HouseofCat.Serialization.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Serialization.Json.Newtonsoft
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.Json.Newtonsoft/HouseofCat.Serialization.Json.Newtonsoft.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Serialization.Json.Utf8Json
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.Json.Utf8Json/HouseofCat.Serialization.Json.Utf8Json.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Serialization.MessagePack
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Serialization.MessagePack/HouseofCat.Serialization.MessagePack.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Sockets
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Sockets/HouseofCat.Sockets.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Sockets.Utf8Json
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Sockets.Utf8Json/HouseofCat.Sockets.Utf8Json.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Utilities
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Utilities/HouseofCat.Utilities.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Windows.Keyboard
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Windows.Keyboard/HouseofCat.Windows.Keyboard.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Windows.NativeMethods
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Windows.NativeMethods/HouseofCat.Windows.NativeMethods.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Windows.Threading
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Windows.Threading/HouseofCat.Windows.Threading.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish HouseofCat.Windows.WMI
      uses: brandedoutcast/publish-nuget@v2.5.2
      continue-on-error: true
      with:
          PROJECT_FILE_PATH: src/HouseofCat.Windows.WMI/HouseofCat.Windows.WMI.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
